version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: locationz
    volumes:
      - .:/locationz
    environment:
          - DATABASE_URL=://root:password@mysql/kubota
          - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1],*
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["/wait-for-it.sh", "db:5432", "--", "/start.sh"]
  
  db:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_HOST=db  # default postgres
      - POSTGRES_PASSWORD=password  # default postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=geo
    ports:
      - "5432:5432"
#   Set a volume some that database is not lost after shutting down the container.
#   I used the name postgres-data but you can changed it to something else.
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgresql/conf:/etc/postgresql/
volumes:
  postgres_data: