version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: locationz
    volumes:
      - .:/locationz
    environment:
          - DATABASE_URL=://root:password@mysql/locationz
          - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1],*
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    container_name: mysql_database
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - /Users/Adam/Development/data/mysql:/var/lib/mysql